services:
  # Qdrant vector database for legal documents (Production)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: production-qdrant
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__LOG_LEVEL: INFO
      QDRANT__STORAGE__STORAGE_PATH: /qdrant/storage
    volumes:
      - qdrant_production_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/6333' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - legal-production-network
    restart: unless-stopped

  # Legal Knowledge Superlinked Production Server
  legal-superlinked:
    build:
      context: .
      dockerfile: production-superlinked.Dockerfile
    container_name: production-legal-superlinked
    environment:
      # Server Configuration
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - LOG_LEVEL=INFO
      - WORKER_COUNT=1
      
      # Database Configuration
      - QDRANT_URL=http://qdrant:6333
      
      # Production Settings
      - ENVIRONMENT=production
      - TRANSFORMERS_CACHE=/app/model_cache
      - GPU_EMBEDDING_THRESHOLD=0
      - DISABLE_RECENCY_SPACE=false
      - ONLINE_PUT_CHUNK_SIZE=1000
      
      # App Configuration
      - APP_MODULE_PATH=simple_example
    depends_on:
      qdrant:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - model_cache_production:/app/model_cache
      - ./output:/app/output:ro
      - ./raw_data:/app/raw_data:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - legal-production-network
    restart: unless-stopped

volumes:
  qdrant_production_data:
    driver: local
  model_cache_production:
    driver: local

networks:
  legal-production-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16